apiVersion: v1
kind: Service
metadata:
  name: ctxEco-backend
  namespace: ctxEco-prod
spec:
  type: ClusterIP
  selector:
    app: ctxEco-backend
  ports:
    - port: 80
      targetPort: 8080
      name: http
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ctxEco-prod
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP

