apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-worker-to-temporal
  namespace: ctxEco-prod
spec:
  podSelector:
    matchLabels:
      app: temporal-server
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: ctxEco-worker
      ports:
        - port: 7233
          protocol: TCP
  policyTypes:
    - Ingress

