apiVersion: v1
kind: Namespace
metadata:
  name: ctxEco-prod
  labels:
    app: ctxEco
    environment: prod
apiVersion: v1
kind: Namespace
metadata:
  name: ctxEco-prod
  labels:
    app.kubernetes.io/name: ctxEco
    app.kubernetes.io/environment: prod


